version: "3.8"
services:
  frontend:
    container_name: kanlen_frontend
    image: tyrelchambers/kanlen_frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped

networks:
  default:
    external:
      name: frontend
